### ISSUE TITLE
New version of dashboard

### ISSUE THREAD

**Issue by glepnir** [glepnir/dashboard-nvim#139]
HI all. I had rewrite dashboard.  I don't have much time to look  issues   that were created when I was hospitalized. if your problem still exist in new version, please create an issue let me know :)

**Comment by Groctel** [comment]
Hey! First of all: Glad to see you're doing fine :D

I've updated to the Lua version and the header is not centered. Appart from that, everything is doing fine. Here's a screenshot:
![image](https://user-images.githubusercontent.com/32376781/173186819-5901c246-7e0f-4d47-bc91-08644ada8bf4.png)

This is my custom configuration: 

```lua
local dashboard = require("dashboard")


local function repeat_str (str, times)
	return times > 0 and str..repeat_str(str, times-1) or ""
end


local empty_line = [[]]
local header = {
	empty_line,
	[[███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗]],
	[[████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║]],
	[[██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║]],
	[[██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║]],
	[[██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║]],
	[[╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝]],
	empty_line
}

local splash = vim.fn.system("shuf -n 1 "..vim.fn.stdpath("config").."/splashes"):sub(1,-2).."!"
local padding = (#header[#header] - #splash) / 2 - 2
splash = repeat_str(" ", padding).."[ "..splash.." ]"

-- Add the splash string followed by two empty lines
table.insert(header, splash)
table.insert(header, empty_line)
table.insert(header, empty_line)
table.insert(header, empty_line)


dashboard.custom_header  = header
dashboard.custom_center = {
	{
		icon = "  ",
		desc = "New file                               ",
		shortcut = ":enew",
		action = "enew",
	},
	{
		icon = "  ",
		desc = "Find file                              ",
		shortcut = "SPC f",
		action = "Telescope find_files hidden=true no_ignore=true",
	},
	{
		icon = "  ",
		desc = "Browse dotfiles                        ",
		shortcut = "SPC v d",
		action = "Telescope find_files cwd=~/.config/nvim/ search_dirs=Ultisnips,lua,viml,init.vim",
	},
	{
		icon = "  ",
		desc = "Update plugins                         ",
		shortcut = ":PackerSync",
		action = "PackerSync",
	},
	{
		icon = "  ",
		desc = "Open floating terminal                 ",
		shortcut = "SPC t t",
		action = "FloatermToggle",
	},
	{
		icon = "  ",
		desc = "Close neovim                           ",
		shortcut = ":qa!",
		action = "qa!",
	},
}
```

The same alignment problem happens without the `splash` line or even without the custom header. I don't have time to look into it just now but if I pick it up before you I'll send a PR ;)

**Comment by glepnir** [comment]
first `db.custom_header` can a function that return a table. and you don't need to set padding ,just return a table like this

```lua
function custom_header()
local header = {
  '',
  '',
  '',
  ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
  ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
  ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
  ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
  ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
  ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
 '',
 '',
}

table.insert(header, your text here)
end

db.custom_header = custom_header
```

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/173189912-36667114-40c6-4021-afd9-491674b6ee7c.png)
I have the same issue, the header was not center

**Comment by glepnir** [comment]
fixed .
![image](https://user-images.githubusercontent.com/41671631/173190133-3fbe64b8-025c-405b-b188-b46ca1abeda3.png)

**Comment by marianpopeanga** [comment]
This breaks anything people had in the configs. Not a very good choice !

**Comment by glepnir** [comment]
@marianpopeanga  sorry for break your config. The new version is faster than old version which use vimscript write. and  more customization.  and i plan to add a new feature that support daily task in dashboard.

**Comment by tin-pham** [comment]
> This breaks anything people had in the configs. Not a very good choice !

I think it easy to change, just look at example at the main page, also it cleaner in lua since the old version use vimscript

**Comment by marianpopeanga** [comment]
the issue is that there are entirely new commands. Everything was working just fine. 
You just don't break compatibility like this. You just wrap it around and keep everything working. If users need it or find useful they can use some variable to switch between these versions. Very basic stuff.

**Comment by glepnir** [comment]
The way to not break any configuration is to do compatible development, but I don't have a lot of time to do compatibility development in dashboard, because there are still many issues in lspsaga, galaxyline that need to be fixed. so I have a lot of work to do. sorry for this

**Comment by ndom91** [comment]
So my vimscript version of `glepnir/dashboard` refused to update actually (which is a good thing! So it didn't just break out of no where). I had to explicitly remove it, and reinstall it to get the new lua version. 

I was able to get everything back up and running how I had it within ~10min of reading through the README.md. Obviously not the greatest move completely changing it without a new branch or pkg name or whatever, but all-in-all was an easy transition to make. I like it! :tada:

**Comment by halafi** [comment]
For me the session management stopped working

`E492: Not an editor command: SessionLoad`

**Comment by glepnir** [comment]
@halafi  yep there had remove session command. I found some session plugin that write in lua .so maybe theme can do it better

**Comment by keyboard-clacker** [comment]
Have you found a good alternative for session management @glepnir ? I was using this and am sad to see it go, though I understand the constraints. Could be nice to link to a replacement if you happen to have one!

**Comment by glepnir** [comment]
@keyboard-clacker   https://github.com/Shatur/neovim-session-manager .I don't use this. but seems like good.

**Comment by halafi** [comment]
I was using [](https://github.com/tpope/vim-obsession) before

**Comment by max397574** [comment]
@marianpopeanga if this breaks your things just pin a commit

it's a good thing when something gets improved

great job glepnir

**Comment by glepnir** [comment]
session support .

**Comment by genmzy** [comment]
没想到突然回来了，注意身体要紧，太卷了确实容易伤身体

**Comment by marianpopeanga** [comment]
@max397574 Of course that i've pin that previous commit.  This is broken for me.
Things SHOULD get improved without braking things what work. 
All the previous commands should have been supported and not just screw things up.

**Comment by keyboard-clacker** [comment]
> @keyboard-clacker https://github.com/Shatur/neovim-session-manager .I don't use this. but seems like good.

Nice this one's solid @glepnir ! Just installed it and got it working and is a great replacement. Just had to turn off a few settings to get it to the same as you had implemented here, but can definitely exactly match behavior. Would you be open to adding a section in the README for this? I'm happy to open a PR for it if yeah

**Comment by glepnir** [comment]
I had readd the session support

**Comment by sprainbrains** [comment]
I have a problem with colorcheme after update. How to fix colors? 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/10284309/174595671-0d2a08c2-4d86-475b-a0dc-58cd4b2885be.png">

**Comment by glepnir** [comment]
@sprainbrains  you should check does your colorscheme have the dashboard highlightgroup. if not. you can highlight them in your config. like `hi DashboardCenterIcon guifg= color code ` etc

**Comment by keyboard-clacker** [comment]
@sprainbrains all of the color groups are detailed on the main README now, I also ran into this and fixed by highlighting all of them

**Comment by sgoudham** [comment]
Hi, I've just upgraded but everything is still not centered as per the screenshot below: 

![image](https://user-images.githubusercontent.com/58985301/174898553-9a5a9b7d-e5d9-4b58-b920-0a0175ddaf97.png)

My config is as follows:
```lua
local dashboard = require("dashboard")

dashboard.custom_header = {
        '                                                       ',
        '                                                       ',
        '                                                       ',
        ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
        ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
        ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
        ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
        ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
        ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
        '                                                       ',
        '                                                       ',
        '                                                       ',
        '                                                       ', 
}
dashboard.custom_center = {
    { 
        icon = '',
        desc = 'Load session                         ',
        shortcut = '<leader> l s',
    },
    { 
        icon = '',
        desc = 'Load Last Session                    ',
        shortcut = '<leader> s l',
    },
}
```

Am I missing some config to make it centred?

**Comment by glepnir** [comment]
@sgoudham  your config works fine in my local 

![image](https://user-images.githubusercontent.com/41671631/175047112-fbc973f9-9dee-41c5-82f3-bb82929e6e03.png)

**Comment by sgoudham** [comment]
I am on Windows 11 so I wonder if that is making a difference? 

I've tested in Windows Terminal and a graphical editor NeoVide which both result in the centering not working properly. 

That's interesting that it works locally for others though. Problem is something with my config or tools 😅

**Comment by glepnir** [comment]
@sgoudham   I don't use windows. but dashboard works fine in @Erven2016 his windows.

**Comment by Erven2016** [comment]
@sgoudham It is normal on Windows 11, with your config.
![image](https://user-images.githubusercontent.com/18652605/175192626-34459cb3-a93e-45ca-8161-8bbffa4b633f.png)

**Comment by sgoudham** [comment]
So it looks like it's an issue with [neovide](https://github.com/neovide/neovide) but I'm unsure what the problem is causing it not to be centred

**Comment by CompanyDATV** [comment]
![image](https://user-images.githubusercontent.com/83489434/175454920-3a0566ca-0b08-4869-aded-949e6318d568.png)
Help me, error packer.nvim by dashboard-nvim

**Comment by glepnir** [comment]
@CompanyDATV  create a new issue for your problem

**Comment by CompanyDATV** [comment]
> @CompanyDATV create a new issue for your problem

how bro :((

**Comment by max397574** [comment]
`new issue` @CompanyDATV

**Comment by experiacc** [comment]
Ok I'm very confused but how are shortcuts supposed to work here? I have tried pressing space key + s + l (which is my leader key also) as well as only a single key (which i prefer). 

But none of these seem to work

![image](https://user-images.githubusercontent.com/82676586/177041484-86ee4619-61d9-4858-83c1-a78d9889371a.png)

**Comment by glepnir** [comment]
it should work . if you use packer try `PackerCompile`. if not work .please create a new issue and fill issue template
