### ISSUE TITLE
Dashboard isn't centered in the buffer

### ISSUE THREAD

**Issue by BooleanCube** [glepnir/dashboard-nvim#93]
The dashboard on my neovim isnt centered and won't resize when the buffer gets smaller which is really annoying.

Screenshots:
![image](https://user-images.githubusercontent.com/47650058/130063043-5ceba387-2101-4aa7-b50e-032f606fd3e2.png)
![image](https://user-images.githubusercontent.com/47650058/130063121-d38e4bb9-c5c9-4b15-8c1e-73ddaaff6ad6.png)

**Comment by BooleanCube** [comment]
I can also see buffer lines which is super annoying

**Comment by sheharyarn** [comment]
Bump, any update on this?

**Comment by BooleanCube** [comment]
fixed

**Comment by sheharyarn** [comment]
Hey, I'm still encountering the issue. How did you fix it?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2355108/151858378-cf5465af-7f5f-4f06-a59e-408ec59432ac.png">

**Comment by BooleanCube** [comment]
sorry, i didn't actually fix it, I switched config over to lua and used alpha.lua

**Comment by sheharyarn** [comment]
Ah got it, thanks for the update. I was actually also considering exploring alpha to see if the bug exists there (and switching if it doesn't). With your comment I assume, it doesn't?

**Comment by BooleanCube** [comment]
> Ah got it, thanks for the update. I was actually also considering exploring alpha to see if the bug exists there (and switching if it doesn't). With your comment I assume, it doesn't?

sorry for the late response, but no I believe it works perfectly fine.
